apiVersion: 1

datasources:
  - name: gdev-loki
    uid: gdev-loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: false
    jsonData:
      manageAlerts: false
